name: Run Unit Tests

on:
  push:
    branches: [ chrome ]
  pull_request:
    branches: [ chrome ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Set up Node.js
        uses: actions/setup-node@v6
        with:
          node-version: '25' # Or a version compatible with your project
      - name: Install dependencies
        run: npm install
      - name: Run unit tests
        run: gulp unit
